---
# CICD Resource Setup
- name: Installing common dependencies
  hosts: all
  become: true
  roles:
    - commons

# Setting up jenkins
- name: Installing jenkins
  hosts: jenkins_server
  become: true
  roles:
    - jenkins_setup
  
# Setting 